name: fake_train_api
description: A Dart API Client for faking API calls to imaginary train API service.
version: 0.0.1
publish_to: 'none'
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  very_good_analysis: ^3.0.0

