name: tickets_api
description: A Dart database implementation to save tickets.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  floor: ^1.3.0


dev_dependencies:
  build_runner: ^2.1.2
  floor_generator: ^1.3.0
  very_good_analysis: ^3.0.0

